name: chewie_vlc
description: A vlc player for Flutter with Cupertino and Material play controls
version: 1.7.1
homepage: https://github.com/voxela-ai/cortexa-chewie-vlc

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_vlc_player_16kb: ^7.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
